"""Configuration settings for the Technician Chatbot application."""

import os
from pathlib import Path
from typing import List
from pydantic import Field
from pydantic_settings import BaseSettings

# Load environment variables from .env file
from dotenv import load_dotenv

# Find the .env and .env.local file in the project root
_project_root = Path(__file__).parent.parent.parent
load_dotenv(dotenv_path=_project_root / ".env.local")
load_dotenv(dotenv_path=_project_root / ".env")
load_dotenv()


class Settings(BaseSettings):
    """Application settings loaded from environment variables."""
    
    # Snowflake Database Configuration (using standardized variable names)
    snowflake_account: str = Field(default="foqukcw-az16310", env="SNOWFLAKE_ACCOUNT")
    snowflake_user: str = Field(default="AUTOTASK_SVC", env="SNOWFLAKE_USER")
    snowflake_password: str = Field(default="", env="SNOWFLAKE_PASSWORD")
    snowflake_authenticator: str = Field(default="keypair", env="SNOWFLAKE_AUTHENTICATOR")
    # Key-pair (RSA) auth — no password / no TOTP. Points at the PKCS#8 private key (.p8)
    # generated by:  openssl genrsa 2048 | openssl pkcs8 -topk8 -inform PEM -out rsa_key.p8 -nocrypt
    snowflake_private_key_path: str = Field(default="", env="SNOWFLAKE_PRIVATE_KEY_PATH")
    snowflake_private_key_pwd: str = Field(default="", env="SNOWFLAKE_PRIVATE_KEY_PWD")
    snowflake_database: str = Field(default="TEST_DB", env="SNOWFLAKE_DATABASE")
    snowflake_schema: str = Field(default="PUBLIC", env="SNOWFLAKE_SCHEMA")
    snowflake_warehouse: str = Field(default="COMPUTE_WH", env="SNOWFLAKE_WAREHOUSE")
    snowflake_role: str = Field(default="ACCOUNTADMIN", env="SNOWFLAKE_ROLE")
    
    # JWT Authentication (using standardized variable names)
    jwt_secret_key: str = Field(default="your-secret-key-change-in-production", env="JWT_SECRET_KEY")
    jwt_algorithm: str = Field(default="HS256", env="JWT_ALGORITHM")
    jwt_access_token_expire_minutes: int = Field(default=30, env="JWT_ACCESS_TOKEN_EXPIRE_MINUTES")
    
    # LLM APIs (using standardized variable names)
    openai_api_key: str = Field(default="", env="OPENAI_API_KEY")
    groq_api_key: str = Field(default="", env="GROQ_API_KEY")
    
    # Application Configuration (using standardized variable names)
    app_host: str = Field(default="0.0.0.0", env="APP_HOST")
    app_port: int = Field(default=8000, env="APP_PORT")
    debug: bool = Field(default=True, env="DEBUG")
    
    # Logging (using standardized variable names)
    log_level: str = Field(default="INFO", env="LOG_LEVEL")
    log_format: str = Field(default="json", env="LOG_FORMAT")
    
    # CORS Configuration (using standardized variable names)
    allowed_origins: str = Field(default="http://localhost:3000,http://localhost:8000,http://127.0.0.1:8000,http://localhost:5173", env="ALLOWED_ORIGINS")

    @property
    def allowed_origins_list(self) -> List[str]:
        """Convert comma-separated origins to list."""
        return [origin.strip() for origin in self.allowed_origins.split(",")]
    
    class Config:
        env_file = ".env"
        case_sensitive = False
        extra = "ignore"  # Ignore extra environment variables


# Global settings instance
settings = Settings()
