-- ==============================================================================
-- TEAMLOGIC AUTOTASK & CTTC NETWORK ONTOLOGY SNOWFLAKE DDL & INGESTION SCRIPT
-- Database: TEST_DB / AUTOTASK_DB
-- Schema: PUBLIC / NETWORK_ONTOLOGY
-- ==============================================================================

USE DATABASE TEST_DB;
USE SCHEMA PUBLIC;

-- 1. Create File Format for CSV Ingestion
CREATE OR REPLACE FILE FORMAT CSV_ONTOLOGY_FORMAT
    TYPE = 'CSV'
    FIELD_DELIMITER = ','
    RECORD_DELIMITER = '\n'
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    NULL_IF = ('NULL', 'null', '')
    EMPTY_FIELD_AS_NULL = TRUE
    ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE;

-- 2. DIM_SITES (Central Offices & Aggregation Sites)
CREATE OR REPLACE TABLE DIM_SITES (
    SITE_ID VARCHAR(64) PRIMARY KEY,
    SITE_NAME VARCHAR(128) NOT NULL,
    SITE_TYPE VARCHAR(64),
    COUNTY VARCHAR(64),
    STATE VARCHAR(32) DEFAULT 'Texas',
    LATITUDE FLOAT,
    LONGITUDE FLOAT,
    ALTITUDE_METERS FLOAT,
    ALTITUDE_FEET FLOAT,
    REGION VARCHAR(64),
    STATUS VARCHAR(32) DEFAULT 'ACTIVE',
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 3. DIM_NETWORK_DEVICES (Routers, Switches, OLTs)
CREATE OR REPLACE TABLE DIM_NETWORK_DEVICES (
    DEVICE_ID VARCHAR(64) PRIMARY KEY,
    DEVICE_NAME VARCHAR(128) NOT NULL,
    VENDOR VARCHAR(64),
    MODEL VARCHAR(64),
    ROLE VARCHAR(64),
    SITE_ID VARCHAR(64) REFERENCES DIM_SITES(SITE_ID),
    MANAGEMENT_IP VARCHAR(64),
    SOFTWARE_RELEASE VARCHAR(64),
    IS_APPROVED_TRAIN BOOLEAN DEFAULT TRUE,
    IS_VERSION_DRIFT_OUTLIER BOOLEAN DEFAULT FALSE,
    ACTIVE_DEFECTS_COUNT NUMBER(4,0) DEFAULT 0,
    DEFECTS_JSON VARIANT,
    SERVICES_COUNT NUMBER(8,0) DEFAULT 0,
    SUBSCRIBERS_COUNT NUMBER(8,0) DEFAULT 0,
    OPER_STATUS VARCHAR(32) DEFAULT 'ONLINE',
    LAST_AUDITED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 4. DIM_PORTS (Physical Interfaces)
CREATE OR REPLACE TABLE DIM_PORTS (
    PORT_ID VARCHAR(128) PRIMARY KEY,
    DEVICE_ID VARCHAR(64) REFERENCES DIM_NETWORK_DEVICES(DEVICE_ID),
    PORT_NAME VARCHAR(64) NOT NULL,
    SPEED_GBPS NUMBER(8,2),
    OPER_STATE VARCHAR(32),
    ADMIN_STATE VARCHAR(32),
    OPTIC_TYPE VARCHAR(64),
    OPTIC_TEMP_C FLOAT
);

-- 5. FACT_TOPOLOGY_LINKS (Physical Trunks, Protected/Unprotected Links)
CREATE OR REPLACE TABLE FACT_TOPOLOGY_LINKS (
    LINK_ID VARCHAR(128) PRIMARY KEY,
    SOURCE_NODE_ID VARCHAR(128) NOT NULL,
    TARGET_NODE_ID VARCHAR(128) NOT NULL,
    RELATIONSHIP_TYPE VARCHAR(64) NOT NULL,
    SPEED_GBPS NUMBER(8,2),
    PROTECTION_ROLE VARCHAR(32) DEFAULT 'protected',
    IS_SPOF_RISK BOOLEAN DEFAULT FALSE,
    LINK_STATUS VARCHAR(32) DEFAULT 'UP',
    PROPERTIES_JSON VARIANT
);

-- 6. DIM_SERVICES (Customer Circuits & EVPN Paths)
CREATE OR REPLACE TABLE DIM_SERVICES (
    SERVICE_ID VARCHAR(128) PRIMARY KEY,
    SERVICE_NAME VARCHAR(128) NOT NULL,
    SERVICE_TYPE VARCHAR(64),
    BANDWIDTH_MBPS NUMBER(12,2),
    SLA_TIER VARCHAR(64),
    DELIVERED_SUBSCRIBER_ID VARCHAR(128),
    STATUS VARCHAR(32) DEFAULT 'HEALTHY',
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 7. DIM_SUBSCRIBERS (Accounts, Enterprises, Mobile Carriers)
CREATE OR REPLACE TABLE DIM_SUBSCRIBERS (
    SUBSCRIBER_ID VARCHAR(128) PRIMARY KEY,
    SUBSCRIBER_NAME VARCHAR(128) NOT NULL,
    ACCOUNT_TYPE VARCHAR(64),
    PRIMARY_SITE_ID VARCHAR(64),
    ACTIVE_CIRCUITS_COUNT NUMBER(6,0) DEFAULT 1,
    MONTHLY_RECURRING_REVENUE_USD NUMBER(12,2),
    STATUS VARCHAR(32) DEFAULT 'ACTIVE'
);

-- 8. DIM_KNOWN_DEFECTS (Vulnerabilities, CVEs, JIRA Cases)
CREATE OR REPLACE TABLE DIM_KNOWN_DEFECTS (
    DEFECT_ID VARCHAR(64) PRIMARY KEY,
    TITLE VARCHAR(256) NOT NULL,
    VENDOR VARCHAR(64),
    AFFECTED_RELEASES VARCHAR(128),
    SEVERITY VARCHAR(32),
    JIRA_CASE_NUMBER VARCHAR(64),
    SYMPTOM_DESCRIPTION VARCHAR(1024),
    RECOMMENDED_REMEDY VARCHAR(1024),
    TOTAL_AFFECTED_DEVICES NUMBER(6,0),
    TOTAL_IMPACTED_SERVICES NUMBER(6,0)
);

-- 9. FACT_INCIDENTS_TICKETS (AutoTask Operational Tickets)
CREATE OR REPLACE TABLE FACT_INCIDENTS_TICKETS (
    TICKET_NUMBER VARCHAR(64) PRIMARY KEY,
    TITLE VARCHAR(256) NOT NULL,
    CATEGORY VARCHAR(64),
    PRIORITY VARCHAR(32),
    STATUS VARCHAR(32),
    AFFECTED_DEVICE_ID VARCHAR(64) REFERENCES DIM_NETWORK_DEVICES(DEVICE_ID),
    ASSOCIATED_DEFECT_ID VARCHAR(64) REFERENCES DIM_KNOWN_DEFECTS(DEFECT_ID),
    BLAST_RADIUS_DEVICES_COUNT NUMBER(6,0) DEFAULT 0,
    IMPACTED_SERVICES_COUNT NUMBER(6,0) DEFAULT 0,
    ASSIGNED_TECHNICIAN VARCHAR(128),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    RESOLUTION_SUMMARY VARCHAR(1024)
);

-- 10. FACT_GRAPH_EDGES (Knowledge Graph Store with VARIANT)
CREATE OR REPLACE TABLE FACT_GRAPH_EDGES (
    EDGE_ID VARCHAR(128) PRIMARY KEY,
    SOURCE_ID VARCHAR(128) NOT NULL,
    TARGET_ID VARCHAR(128) NOT NULL,
    REL_TYPE VARCHAR(64) NOT NULL,
    PROPERTIES_VARIANT VARIANT,
    INGESTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 11. ADMIN_USERS (Enterprise Administrator Accounts)
CREATE OR REPLACE TABLE ADMIN_USERS (
    ADMIN_ID VARCHAR(64) PRIMARY KEY,
    USERNAME VARCHAR(64) NOT NULL UNIQUE,
    EMAIL VARCHAR(128) NOT NULL,
    FULL_NAME VARCHAR(128),
    ROLE VARCHAR(32) DEFAULT 'admin',
    PERMISSIONS_SCOPE VARCHAR(512),
    STATUS VARCHAR(32) DEFAULT 'ACTIVE',
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 12. DIM_TECHNICIAN_SHIFTS_SKILLS (Technician Roster, Shifts & Skills)
CREATE OR REPLACE TABLE DIM_TECHNICIAN_SHIFTS_SKILLS (
    TECHNICIAN_ID VARCHAR(64) PRIMARY KEY,
    USERNAME VARCHAR(64) NOT NULL UNIQUE,
    FULL_NAME VARCHAR(128) NOT NULL,
    EMAIL VARCHAR(128),
    PHONE_NUMBER VARCHAR(64),
    PRIMARY_SHIFT VARCHAR(64) DEFAULT 'Morning (08:00 - 16:00)',
    ON_CALL_STATUS VARCHAR(32) DEFAULT 'Standby',
    SKILL_SETS VARCHAR(512),
    EXPERIENCE_LEVEL VARCHAR(64) DEFAULT 'L2 Specialist',
    STATUS VARCHAR(32) DEFAULT 'ACTIVE',
    CURRENT_TICKETS_LOAD NUMBER(4,0) DEFAULT 0,
    MAX_CAPACITY NUMBER(4,0) DEFAULT 10
);

-- ==============================================================================
-- INGESTION COMMANDS (Run after uploading CSV files to Snowflake Stage)
-- Example Stage: @ONTOLOGY_STAGE
-- ==============================================================================
-- COPY INTO DIM_SITES FROM @ONTOLOGY_STAGE/DIM_SITES.csv FILE_FORMAT = (FORMAT_NAME = CSV_ONTOLOGY_FORMAT);
-- COPY INTO DIM_NETWORK_DEVICES FROM @ONTOLOGY_STAGE/DIM_NETWORK_DEVICES.csv FILE_FORMAT = (FORMAT_NAME = CSV_ONTOLOGY_FORMAT);
-- COPY INTO DIM_PORTS FROM @ONTOLOGY_STAGE/DIM_PORTS.csv FILE_FORMAT = (FORMAT_NAME = CSV_ONTOLOGY_FORMAT);
-- COPY INTO FACT_TOPOLOGY_LINKS FROM @ONTOLOGY_STAGE/FACT_TOPOLOGY_LINKS.csv FILE_FORMAT = (FORMAT_NAME = CSV_ONTOLOGY_FORMAT);
-- COPY INTO DIM_SERVICES FROM @ONTOLOGY_STAGE/DIM_SERVICES.csv FILE_FORMAT = (FORMAT_NAME = CSV_ONTOLOGY_FORMAT);
-- COPY INTO DIM_SUBSCRIBERS FROM @ONTOLOGY_STAGE/DIM_SUBSCRIBERS.csv FILE_FORMAT = (FORMAT_NAME = CSV_ONTOLOGY_FORMAT);
-- COPY INTO DIM_KNOWN_DEFECTS FROM @ONTOLOGY_STAGE/DIM_KNOWN_DEFECTS.csv FILE_FORMAT = (FORMAT_NAME = CSV_ONTOLOGY_FORMAT);
-- COPY INTO FACT_INCIDENTS_TICKETS FROM @ONTOLOGY_STAGE/FACT_INCIDENTS_TICKETS.csv FILE_FORMAT = (FORMAT_NAME = CSV_ONTOLOGY_FORMAT);
-- COPY INTO FACT_GRAPH_EDGES FROM @ONTOLOGY_STAGE/FACT_GRAPH_EDGES.csv FILE_FORMAT = (FORMAT_NAME = CSV_ONTOLOGY_FORMAT);
-- COPY INTO ADMIN_USERS FROM @ONTOLOGY_STAGE/ADMIN_USERS.csv FILE_FORMAT = (FORMAT_NAME = CSV_ONTOLOGY_FORMAT);
-- COPY INTO DIM_TECHNICIAN_SHIFTS_SKILLS FROM @ONTOLOGY_STAGE/DIM_TECHNICIAN_SHIFTS_SKILLS.csv FILE_FORMAT = (FORMAT_NAME = CSV_ONTOLOGY_FORMAT);
